@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzg3MTk1NzMsInN1YiI6IjAxOWUxOWZiLTA1NWMtN2I1Yi04MTAxLWVkNjUwNDNhNWQ3NCJ9.6IcLbymWP2pZz2_qNSfObZO-hN5siNBOFKrDUG7TiOA
###
POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "name": "Sample Product",
  "price": 19.99
}
###
GET http://localhost:8000/products/019bfd58-8e98-761b-a64f-6328e37f7815 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
###
PUT http://localhost:8000/products/019bfd58-8e98-761b-a64f-6328e37f7815 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Product",
  "price": 29.99
}
###
DELETE http://localhost:8000/products/019bfd58-8e98-761b-a64f-6328e37f7816 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
###
GET http://localhost:8000/products?page=1&limit=3 HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
###
GET http://localhost:8000/products?page=1&limit=3&sort=desc HTTP/1.1
Accept: application/json
Authorization: Bearer {{token}}
