//@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Nzg3MjQwNjAsInN1YiI6IjAxOWUxOWZiLTA1NWMtN2I1Yi04MTAxLWVkNjUwNDNhNWQ3NCJ9.Wuuu8e00kl2ErSga_2qgiLkWVc01xYNam3BCKMhcgbw

@authToken = {{login.response.body.access_token}}
###

# @name login
POST http://localhost:8000/users/generate-token HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  
  "email": "ana.julias@testuser.com",
  "password": "password123"
}
###
POST http://localhost:8000/products HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Sample Product",
  "price": 19.99
}
###
//@authToken = {{login.response.body.access_token}}
GET http://localhost:8000/products/019bfd58-8e98-761b-a64f-6328e37f7815 HTTP/1.1
Accept: application/json
Authorization: Bearer {{authToken}}
###
PUT http://localhost:8000/products/019bfd58-8e98-761b-a64f-6328e37f7815 HTTP/1.1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Updated Product",
  "price": 29.99
}
###
DELETE http://localhost:8000/products/019bfd58-8e98-761b-a64f-6328e37f7816 HTTP/1.1
Accept: application/json
Authorization: Bearer {{authToken}}
###
GET http://localhost:8000/products?page=1&limit=3 HTTP/1.1
Accept: application/json
Authorization: Bearer {{authToken}}
###
GET http://localhost:8000/products?page=1&limit=3&sort=desc HTTP/1.1
Accept: application/json
Authorization: Bearer {{authToken}}
